import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import SidebarAdmin from "@/components/shared/sidebarAdmin";
import HeaderAdmin from "@/components/shared/headerAdmin";
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "BoHaven | Quản trị hệ thống",
    description: "Generated by create next app",
};

export default function AdminLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (

        <div
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
            <div className="md:h-screen relative overflow-hidden">
                <div className="flex h-full w-full">
                    <SidebarAdmin />
                    <div className="flex flex-col w-full">
                        <HeaderAdmin />
                        {children}
                    </div>
                </div>
            </div>
        </div>

    );
}
